### ISSUE TITLE
How to organize the different datapackage-*-py packages?

### ISSUE THREAD

**Issue by vitorbaptista** [okfn/datapackage-py#23]
The code that works with DataPackages is split in three repositories:

* https://github.com/okfn/datapackage-py -- Main package for loading/parsing/creating Data Packages and its resources;
* https://github.com/okfn/datapackage-validate-py -- Validates Data Packages according to specific schemas;
* https://github.com/okfn/datapackage-registry-py -- Loads schemas from the registry at https://github.com/dataprotocols/schemas

# Advantages

1. Forces a modular coding style;
2. Allows the users to cherry pick what parts of the code they need;
3. Each package can have a separate release cycle.

# Disadvantages

1. Requires extra code to maintain each package;
2. Complicates exception handling;
3. The development cycle is worsened.

**Comment by vitorbaptista** [comment]
Talking about the advantages, `1` would probably improve the code (being modular good), and using separate packages kind of forces it. It's not the only way, though. There're many other techniques to improve modularity (methods, classes, packages, ...) that don't require being a separate package.

`2` is good, but I'm not sure how important this is. For such a small package, I'd say it's negligible.

`3` is also good, but the packages are so intertwined that I don't see a time where we would (say) upgrade the `datapackage-validate-py` but not upgrade `datapackage-py`.

Talking about the disadvantage `2`, I think that most (all?) exceptions that are thrown by a package should be wrapped in a custom exception class to avoid coupling our users' code with our dependencies' code. For example, we use `jsonschema` to validate data against a certain schema. It throws a `jsonschema.exceptions.ValidationError` when the data is invalid. If we don't wrap this exception in a custom class, our users would have to be aware that we use `jsonschema` and actually import `jsonschema.exceptions` if they want to catch it. This means that if we change from `jsonschema` to another dependency, we'll break our users' code.

The same point can be made for exceptions thrown by (say) `datapackage-validate-py` when using `datapackage-py`. If we don't wrap those, the user will need to import from `datapackage_validate.exceptions` and catch them herself.

About disadvantage `3`, what happens if we improve/update `datapackage_registry`? We need to push it to pypi, then move to `datapackage_validate`, update its dependencies, test, then push it to pypi, and then move to `datapackage` and do the same. This will be needed on every change.

**Comment by vitorbaptista** [comment]
Some examples the approach of similar packages, https://www.npmjs.com/package/csv is split in 4 packages, https://github.com/simplejson/simplejson is on a single package.

The main argument is to follow UNIX's philosophy of doing only one thing. I agree with it, the difference is in what is "one thing". For me, reading/validating/writing data packages is one thing. You could even argue that the validation is already separated in another package: `jsonschema`. This being the case, my suggestion would be to merge `datapackage-validate-py` into `datapackage-py`.

The registry is different. Although I would be inclined to merge it into `datapackage-py` as well, I see why we might want to keep it in a separate repository.

**Comment by pwalsh** [comment]
Thanks @vitorbaptista for addressing this here. I'm obviously quite biased as it is my call to design the packages like this, and I'd love to hear from anyone, and especially @roll and @brew who have worked on these codebases too.

You've covered most of the important points above, and instead of addressing everything one by one I'll just outline why I think it is a *much* better approach to keep these packages modular.

1. I think most of the pain points you mentioned are actually related to the initial effort of creating these libs, and will not manifest for ongoing work once we publish to pypi
2. I do believe that enforcing modularity helps improve our overall API design, but I also grant that this can be achieved in other ways, with discipline.
3. I think that these libs do have different release trajectories going forward. the `registry` and `validate` libs will almost stop development once we publish to pypi, whereas the main lib will like get new features
4. Related to above, there are clear use cases for just using the `validate` lib as a utility in various places that we work with `datapackage.json` and don't need to interact with an instance at all (e.g.: https://github.com/openspending/os-cli/blob/master/requirements.txt#L4)
5. As you point out, the `registry` is a good candidate for a standalone package. Likewise, in the js lib of the registry we have used it in such a way for UI selectors. Granted this is less related for the python lib.
6. Lastly, but perhaps no less important from my perspective in terms of trying to bring some consistency to OKI's technical output, albeit much more subjective than the above points, I like consistency across the `js` and `py` codebases for the Frictionless Data libs as a way to track coverage and implementation of our spec work around Data Package and JSON Table Schema.

**Comment by brew** [comment]
I can see it from both perspectives. I like the modular approach, but definitely see the problems identified by @vitorbaptista, particularly around unifying an approach to exception handling. Similar to @vitorbaptista examples, I'm led to thinking about the toolkit approach, e.g. csvkit (https://csvkit.readthedocs.org/en/0.9.1/cli.html), which has many separate tools that do one thing, which a user would rarely need to use all of, but housing them together is convenient when a user wants to combine some of them. They clearly remain separate utilities within the package though, which requires some discipline.

However, keeping things modular means that if a module takes off in an unexpected direction with a lot of useful development, it can do so without infringing on the purpose of the other modules.

**Comment by pwalsh** [comment]
@brew thanks for contributing.

As for the specific issue of exceptions - I'm not sure why this is a pain point - we have dependencies; we wrap their exceptions. This is relevant for any dependency that can raise for a consumer, and is not a specific issue related to breaking out `registry`, `validate` and `model` into distinct packages.

**Comment by vitorbaptista** [comment]
@pwalsh You could merge the issue with the exceptions as part of the "extra boilerplate (and docs) needed". It would also feel weird for me as an user of the packages. If I'm using `datapackage_validate` and call `validate()` I would have to catch `DataPackageValidateException`, but if I'm using `datapackage` and call `validate()`, I would have to catch `datapackage.exceptions.ValidationError`.

Following this approach of many small but tightly correlated packages, it feels like we should have a `datapackage-exceptions-py` to be able to use the same exceptions across the packages.

**Comment by pwalsh** [comment]
@vitorbaptista why should we, as designers of the libs, expose the same error under different names? In the case you mention, why would we not just expose the `validate` exceptions via the `datapackage` exceptions module?

**Comment by vitorbaptista** [comment]
You mean write in datapackage's `exceptions.py` something like:

```python
import datapackage_validate.exceptions

ValidationError = datapackage_validate.exceptions.ValidationError
```

**Comment by pwalsh** [comment]
@vitorbaptista I guess. I've not experienced the this as a problem so I trying to understand it and suggest solutions. 

For me personally, I don't see the issue at all - I use libs in Python **all the time** that raise exceptions from their dependencies. I just grabbed an example now - the [CKAN API client](https://github.com/ckan/ckanapi/blob/master/ckanapi/errors.py#L1) which heavily depends on `requests` and does not attempt to wrap exceptions that `requests` raises in order to simplify the surface of exception handling for calling code.

So, just really having a hard time right now understanding why exception handling is such a manifest issue here **because of** the modular libraries, and how the case we have here is somehow at odds with the general Python ecosystem.

It is the main thing from your original points that I'm concerned we get right, so this is why I'm asking for more info.

**Comment by vitorbaptista** [comment]
The reasoning for wrapping extensions is to avoid client code being coupled with our dependencies. For example, `datapackage.validate()` uses `jsonschema`, basically just calling `jsonschema.validate(schema, data)`. This method call is wrapped in a try/except block, which wraps the `jsonschema.ValidationError` exceptions raised into a `datapackage.exceptions.ValidationError`. This way, the user doesn't need to know that we use `jsonschema`, and so isn't tied to our dependencies' code.

If we really follow through the separation of packages, there should not be a difference between the way we handle exceptions coming from `jsonschema` or from `datapackage_validate`. This is the problem I was talking about earlier.

It's not a major issue, but still is one of the disadvantages I've seen so far.

**Comment by vitorbaptista** [comment]
Given that our chat here has died down, and neither @brew nor @roll seem to have a strong preference any way or other (correct me if I'm wrong), I'll close this. The refactoring to extract validation from this repository is tracked on https://github.com/okfn/datapackage-py/issues/22.
